## Anissea Reed - Section 5 Homework

1. Pandas stands for either 
    * Python Data
    * Python Data Analysis

1. The two collections Pandas uses is Series and Dataframe.

1. 4 things Pandas can do 
    * Data Cleansing 
    * Data normalization 
    * Data visualization
    * Data inspection 

1. To permanently sort a Dataframe one should use inplace = True 

1. A CSV or a Comma Separted Values file contains plain text in a well known format that can be used by everyone.

1. When cleaning data we do not like NULLs in our data.


In [1]:
import numpy as np

# 7. Creating an array using np.zeros

arr1 = np.zeros((2, 3, 2))
print(arr1)

# 8. Using .linspace() to create an array with 6 values between 1 and 20

arr2 = np.linspace(1, 20, 6)
print(arr2) 

# 9. Making a deep copy of arr2 into arr3

arr3 = arr2.copy()
print(arr3)



[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[ 1.   4.8  8.6 12.4 16.2 20. ]
[ 1.   4.8  8.6 12.4 16.2 20. ]


In [3]:
# 10. Concatening 3 Arrays

arr4 = np.array([[25, 16]])
arr5 = np.array([[11, 2], [13, 4]])
arr6 = np.array([[7, 81], [5, 6], [11, 12]])
newArray = np.concatenate((arr4, arr5, arr6), axis=0)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [4]:
# 11. Sorting "newArray" 

sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [5]:
# 12. Unpacking the array tuples into 4 variables

tuple1 = newArray[0:1]
tuple2 = newArray[1:3]
tuple3 = newArray[3:5]
tuple4 = newArray[5:6]
print(tuple1)
print(tuple2)
print(tuple3)
print(tuple4)

[[25 16]]
[[11  2]
 [13  4]]
[[ 7 81]
 [ 5  6]]
[[11 12]]


In [6]:
# 13. Concatenating three arrays together then sorting them

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7]) 
print(one)
print(two)
print(three)

comboArray = np.concatenate((one, two, three))
print(comboArray)

sortedcomboArray = np.sort(comboArray)
print(sortedcomboArray)


[10 11 12 13 14 15 16 17]
[20 21 22 23 24 25 26 27]
[0 1 2 3 4 5 6 7]
[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [ ]:
# 14. Slicing comboArray

sec1 = sortedcomboArray[1:2]
print(sec1)
sec2 = sortedcomboArray[2:24]
print(sec2)
sec3 = sortedcomboArray[3:15]
print(sec3)
sec4 = sortedcomboArray[-6:]
print(sec4)
sec5 = sortedcomboArray[:-8]
print(sec5)
sec6 = sortedcomboArray[20::2]
print(sec6)
sec7 = sortedcomboArray[::-5]
print(sec7)

[1]
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [ ]:
import pandas as pd

# Creating a Dataframe named Dinner

Dinner = {
    "Ingredients": ["Flour", "Milk", "Eggs", "Spam"],
    "Quantity": [4, 1, 2, 1],
    "Unit": ["cups", "cup", "large", "can"]
}
Results = pd.DataFrame(Dinner)
print(Results)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [21]:
import pandas as pd

# Creating a Dataframe named studentData 

studentData = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'Paddleboarding', 'Cricket']
}
studentData = pd.DataFrame(studentData)
print(studentData)

# Adding deserts series to the dataframe

deserts = pd.Series(['ice cream', 'Cashew Fudge', 'waffels', 'Carrot Halwa'])
print(deserts)

studentData['Deserts'] = deserts
print(studentData)

# Sorting by column "Name" and "address"

sortedstudentData = studentData.sort_values(by= ['Name', 'address'], ascending=True, inplace=True)
print(sortedstudentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  Paddleboarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
0       ice cream
1    Cashew Fudge
2         waffels
3    Carrot Halwa
dtype: object
      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  Paddleboarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  
None


In [20]:
import pandas as pd

# Creating a Dataframe named "cows_and_goats"

cows_and_goats = pd.DataFrame(
        {'Cows': [12, 20], 
         'Goats': [22, 19]}, 
         index=['Year 1', 'Year 2']
)
print(cows_and_goats)

# Saving "cows_and_goats" as a CSV file

studentData.to_csv("C:/Users/Anissea/Documents/cows_and_goats.csv", index=False)

        Cows  Goats
Year 1    12     22
Year 2    20     19


In [26]:
import pandas as pd

# Creating a Dataframe about vegetable data

vegetableData = {
    'Vegetable': ['Celery', 'Cucumbers', 'Carrots', 'Tomatoes', 'Potatoes'],
    'Quantity': [4, 6, 12, 8, 20],
    'Price': [1.5, 1.0, 0.5, 1.75, 0.25]
}
vegetableData = pd.DataFrame(vegetableData)
print(vegetableData)

# Saving vegetableData as a CSV file

vegetableData.to_csv("C:/Users/Anissea/Documents/vegetableData.csv", index=False)

# Making changes to "Price" column in vegetableData

vegetableData['Price'] = [2.0, 2.5, 1.0, 3.0, 0.75]
print(vegetableData)

# Updating vegetableData CSV file

vegetableData.to_csv("C:/Users/Anissea/Documents/vegetableData-updated.csv", index=False)

   Vegetable  Quantity  Price
0     Celery         4   1.50
1  Cucumbers         6   1.00
2    Carrots        12   0.50
3   Tomatoes         8   1.75
4   Potatoes        20   0.25
   Vegetable  Quantity  Price
0     Celery         4   2.00
1  Cucumbers         6   2.50
2    Carrots        12   1.00
3   Tomatoes         8   3.00
4   Potatoes        20   0.75
